apiVersion: v1
kind: Namespace
metadata:
  name: control-plane
  labels:
    stimpact.ai/role: control-plane
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    stimpact.ai/role: sandbox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stimpact-control-plane
  namespace: control-plane
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_CONTROL_PLANE_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stimpact-sandbox-job
  namespace: sandbox
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_SANDBOX_JOB_ROLE_ARN
