apiVersion: v1
kind: Namespace
metadata:
  name: control-plane
  labels:
    stimpact.ai/role: control-plane
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    stimpact.ai/role: sandbox
